site_name: C 语言技术面试

nav:
    - 首页: index.md
    - 基础知识: basic/
    - 算法相关: algorithm/
    - 领域相关: tech-area/
    - 项目经验: projects/

plugins:
    - search
    - redirects:
        redirect_maps:
            basic/basic_algorithm.md: algorithm/basic.md
    - autorefs
    - literate-nav:
        implicit_index: true
